import { motion } from "framer-motion";
import { FiLayers, FiBarChart2, FiBell, FiGithub, FiArrowRight } from "react-icons/fi";
import "./Projects.css";

const PROJECTS = [
  {
    title: "SkillMatch",
    category: "Full Stack Web Application",
    description:
      "A full-stack internship and skill-matching platform that helps students discover internship opportunities based on their skills, education, experience, and career interests. Companies can post internships, manage applicants, and review skill match scores generated by the system.",
    tech: ["React", "Supabase", "JavaScript", "CSS", "Git"],
    icon: <FiLayers />,
    featured: true,
    detailsLink: "#",
    githubLink: "#",
  },
  {
    title: "DataLens",
    category: "Data Analytics System",
    description:
      "A rule-based data analytics and visualization platform designed to help users organize, interpret, and understand datasets through an intuitive dashboard and insightful visual reports.",
    tech: ["React", "JavaScript", "Chart.js", "CSS"],
    icon: <FiBarChart2 />,
    featured: false,
    detailsLink: "#",
    githubLink: "#",
  },
  {
    title: "LibAlert",
    category: "Library Management System",
    description:
      "A modern library notification and management system that helps students receive book availability updates, due-date reminders, and library announcements through an organized interface.",
    tech: ["React", "JavaScript", "CSS"],
    icon: <FiBell />,
    featured: false,
    detailsLink: "#",
    githubLink: "#",
  },
];

const containerVariants = {
  hidden: {},
  visible: {
    transition: { staggerChildren: 0.15 },
  },
};

const cardVariants = {
  hidden: { opacity: 0, y: 30 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.55, ease: "easeOut" } },
};

export default function Projects() {
  return (
    <motion.section
      id="projects"
      className="section projects"
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.1 }}
      transition={{ duration: 0.6, ease: "easeOut" }}
    >
      <div className="container">
        <h2 className="section-title">Projects</h2>
        <p className="projects-subtitle">
          Here are some of the projects I've worked on throughout my learning
          journey.
        </p>

        <motion.div
          className="projects-grid"
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.1 }}
        >
          {PROJECTS.map((project) => (
            <motion.article
              className="card project-card"
              key={project.title}
              variants={cardVariants}
              whileHover={{ y: -8 }}
              transition={{ duration: 0.25, ease: "easeOut" }}
            >
              {project.featured && (
                <span className="project-featured-badge">Featured</span>
              )}

              <div className="project-icon" aria-hidden="true">
                {project.icon}
              </div>

              <span className="project-category">{project.category}</span>
              <h3 className="project-title">{project.title}</h3>
              <p className="project-description">{project.description}</p>

              <div className="project-tech-list">
                {project.tech.map((tech, index) => (
                  <motion.span
                    className="project-tech-badge"
                    key={tech}
                    initial={{ opacity: 0 }}
                    whileInView={{ opacity: 1 }}
                    viewport={{ once: true, amount: 0.6 }}
                    transition={{ duration: 0.35, delay: index * 0.06 }}
                    whileHover={{ scale: 1.08 }}
                  >
                    {tech}
                  </motion.span>
                ))}
              </div>

              <div className="project-actions">
                <motion.a
                  href={project.detailsLink}
                  className="btn project-btn-primary"
                  whileHover={{ scale: 1.04 }}
                  whileTap={{ scale: 0.98 }}
                  transition={{ duration: 0.2 }}
                  aria-label={`View details for ${project.title}`}
                >
                  View Details
                  <FiArrowRight />
                </motion.a>
                <motion.a
                  href={project.githubLink}
                  className="project-btn-secondary"
                  whileHover={{ scale: 1.04 }}
                  whileTap={{ scale: 0.98 }}
                  transition={{ duration: 0.2 }}
                  aria-label={`View ${project.title} source code on GitHub`}
                >
                  <FiGithub />
                  GitHub
                </motion.a>
              </div>
            </motion.article>
          ))}
        </motion.div>
      </div>
    </motion.section>
  );
}
